from JanggiGame import JanggiGame
from JanggiGame import Board
from JanggiGame import Piece
from JanggiGame import Player
from JanggiGame import Chariot

game: JanggiGame = JanggiGame()
game.display_board()
# # game.make_move("c10", "d8")
# # game.display_board()
# # game.make_move("a4", "a5")
# # game.display_board()
# # game.make_move("d8", "e6")
# # game.display_board()
#
#
# game.make_move("a10", "a9")
# game.display_board()
# game.make_move("a4", "a5")
# game.display_board()
# game.make_move("a9", "c9")
# game.display_board()
# game.make_move("a5", "a6")
# game.display_board()
# game.make_move("d10", "e10")
# game.display_board()
# game.make_move("a6", "a7")
# game.display_board()
# game.make_move("c9", "d9")
# game.display_board()
# game.make_move("a7", "a8")
# game.display_board()
# game.make_move("d9", "d10")
# game.display_board()
# game.make_move("a8", "a9")
# game.display_board()
# game.make_move("d10", "f8")
# game.display_board()
# game.make_move("e9", "e8")
# game.display_board()
# game.make_move("a9", "a10")
# game.display_board()
# game.make_move("d10", "f8")
# game.display_board()
# game.make_move("a10", "b10")
# game.display_board()
# game.make_move("f8", "f9")
# game.display_board()
# game.make_move("b10", "c10")
# game.display_board()
# game.make_move("e8", "f8")
# game.display_board()
# game.make_move("c10", "d10")
# game.display_board()
# game.make_move("f9", "e8")
# game.display_board()
# game.make_move("f9", "e9")
# game.display_board()
# game.make_move("d10", "c10")
# game.display_board()
# game.make_move("h10", "f9")
# game.display_board()

game.make_move("c7", "c6")
game.display_board()
game.make_move("a4", "a5")
game.display_board()
game.make_move("a7", "b7")
game.display_board()
game.make_move("a5", "a6")
game.display_board()
game.make_move("b8", "b6")
game.display_board()
game.make_move("a6", "a7")
game.display_board()
game.make_move("b6", "b6")
game.display_board()
game.make_move("c4", "b4")
game.display_board()
game.make_move("c6", "c5")
game.display_board()
game.make_move("b4", "b4")
game.display_board()
game.make_move("c5", "b5")
game.display_board()
game.make_move("b4", "b4")
game.display_board()
game.make_move("b6", "b4")
game.display_board()




